name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /root/birdhelper
          git pull
          
          # 继续执行后续命令
          docker build -t slack-bot . --no-cache
          docker stop slack-bot || true
          docker rm slack-bot || true
          docker run -d --name slack-bot -p 5000:5000 slack-bot
